# Generated by Django 4.2.5 on 2024-02-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
